[metadata]
name = lcmaker
author = Robby Wilson
author_email = robert.f.wilson@nasa.gov
license = Other
license_files = licenses/LICENSE.rst
url = https://github.com/robertfwilson/romanlcmaker
description = all in one package to simulate various light curves for the GBTDS
long_description = file: README.rst
long_description_content_type = text/x-rst
edit_on_github = False
github_project = robertfwilson/romanlcmaker

[options]
zip_safe = False
packages = find:
python_requires = >=3.10
setup_requires = setuptools_scm
install_requires =
    numpy
    scipy
    astropy


[options.extras_require]
test =
    pytest-astropy
docs =
    sphinx-astropy

[options.package_data]
lcmaker = data/*

[tool:pytest]
testpaths = "lcmaker" "docs"
astropy_header = true
doctest_plus = enabled
text_file_format = rst
addopts = --doctest-rst

[coverage:run]
omit =
    lcmaker/_astropy_init*
    lcmaker/conftest.py
    lcmaker/*setup_package*
    lcmaker/tests/*
    lcmaker/*/tests/*
    lcmaker/extern/*
    lcmaker/version*
    */lcmaker/_astropy_init*
    */lcmaker/conftest.py
    */lcmaker/*setup_package*
    */lcmaker/tests/*
    */lcmaker/*/tests/*
    */lcmaker/extern/*
    */lcmaker/version*

[coverage:report]
exclude_lines =
    # Have to re-enable the standard pragma
    pragma: no cover
    # Don't complain about packages we have installed
    except ImportError
    # Don't complain if tests don't hit assertions
    raise AssertionError
    raise NotImplementedError
    # Don't complain about script hooks
    def main\(.*\):
    # Ignore branches that don't pertain to this version of Python
    pragma: py{ignore_python_version}
    # Don't complain about IPython completion helper
    def _ipython_key_completions_
